# Problems :

1.Prepare a array of all zeros (3 rows and 4 columns)

In [1]:
import numpy as np

array = np.zeros((3, 4))
print(array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2.Create an array with random input elements (shape - 2,3,5)

In [5]:
import numpy as np
shape = -2
array = np.random.rand(2, 3, 5)
print(array)


[[[0.02952788 0.35880852 0.32414215 0.5960757  0.33318152]
  [0.42887389 0.34326993 0.68979886 0.61680605 0.45395037]
  [0.74384604 0.01254645 0.4258268  0.14841717 0.65149528]]

 [[0.06552056 0.08857473 0.18077104 0.41833013 0.70850303]
  [0.37298799 0.80709867 0.85347521 0.22986994 0.81051338]
  [0.62477904 0.18013025 0.30378641 0.00570523 0.03606678]]]


3.Create two arrays (numbers between 10 -20), First array shape= (2,3,5), Second array shape =(1,3,5).
Now multiply them
Find the min Axis= 1 wise
Find the sum Axis= 0 wise


In [7]:
import numpy as np

array1 = np.random.randint(10, 20, (2, 3, 5))
array2 = np.random.randint(10, 20, (1, 3, 5))

# Multiply arrays
mult = array1 * array2

# Find minimum along axis 1
min_axis_1 = np.amin(mult, axis=1)
print("Minimum along axis 1:")
print(min_axis_1)

# Find sum along axis 0
sum_axis_0 = np.sum(mult, axis=0)
print("Sum along axis 0:")
print(sum_axis_0)


Minimum along axis 1:
[[165 120 208 160 168]
 [150 182 272 160 168]]
Sum along axis 0:
[[370 434 665 400 589]
 [315 310 540 462 336]
 [527 594 480 340 434]]
